# Cloud Build: Build image and deploy to Cloud Run
# Usage:
# gcloud builds submit --config=cloudbuild.yaml \
#   --substitutions=_SERVICE=safesnap-backend,_REGION=us-central1,_CLOUDSQL_INST=my-project-121-387614:us-central1:safesnap

options:
  substitutionOption: ALLOW_LOOSE

substitutions:
  _SERVICE: "safesnap-backend"
  _REGION: "us-central1"
  _CLOUDSQL_INST: ""

steps:
  # Build image from Dockerfile
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/${_SERVICE}:${SHORT_SHA}", "."]

  # Push image
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/${_SERVICE}:${SHORT_SHA}"]

  # Deploy to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
      - -c
      - |
        set -euo pipefail
        IMAGE="gcr.io/$PROJECT_ID/${_SERVICE}:${SHORT_SHA}"
        REGION="${_REGION}"
        echo "Deploying $IMAGE to Cloud Run ($REGION)"
        EXTRA_SQL_FLAG=""
        if [[ -n "${_CLOUDSQL_INST}" ]]; then
          EXTRA_SQL_FLAG="--add-cloudsql-instances ${_CLOUDSQL_INST}"
        fi
        gcloud run deploy "${_SERVICE}" \
          --image "${IMAGE}" \
          --platform managed \
          --region "${REGION}" \
          --allow-unauthenticated \
          --set-env-vars SPRING_PROFILES_ACTIVE=production \
          --memory "1Gi" \
          --cpu "1" \
          --concurrency "80" \
          ${EXTRA_SQL_FLAG}

images:
  - "gcr.io/$PROJECT_ID/${_SERVICE}:${SHORT_SHA}"
