version: '3.8'

services:
  db:
    image: postgres:15
    container_name: safesnap-db
    restart: always
    environment:
      POSTGRES_USER: safesnap
      POSTGRES_PASSWORD: safesnap123
      POSTGRES_DB: safesnapdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
